
POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "87495b95-1c7f-4038-ae55-ab36ed6a9411"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "f8df753c-3b58-43aa-8016-12aaa4f1ea3e",
    "account_id_to": "0216ea38-524f-4e85-8743-d484a8f7538e",
    "amount": 1
}